apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kobo

resources:
  - ../../base
  - ingress.yaml

secretGenerator:
  - name: hebban-secret
    files:
      - users.json=secrets/users.json
    options:
      disableNameSuffixHash: true

images:
  - name: ghcr.io/mortenzwarenstein/kobo-hebban-adapter
    newTag: latest
